export const organDescriptions: Record<string, string> = {
	adrenal_gland_left: "A small hormone-making gland that sits on top of the left kidney. It helps control your stress response, blood pressure, and metabolism.",
	adrenal_gland_right: "A small hormone-making gland that sits on top of the right kidney. It helps control your stress response, blood pressure, and metabolism.",
	aorta: "The body's main artery. It carries oxygen-rich blood from the heart down through the chest and abdomen to everything below.",
	bladder: "The hollow, stretchy organ that stores urine until you're ready to empty it.",
	celiac_artery: "A short, major artery branching off the aorta that feeds the liver, stomach, and spleen.",
	colon: "The large intestine. It pulls water back out of digested food and forms stool.",
	common_bile_duct: "The tube that carries bile from the liver and gallbladder into the small intestine to help digest fat.",
	duodenum: "The first stretch of the small intestine, right after the stomach, where digestion really gets going.",
	femur_left: "The thigh bone of the left leg. It's the longest, strongest bone in the body.",
	femur_right: "The thigh bone of the right leg. It's the longest, strongest bone in the body.",
	gall_bladder: "A small sac tucked under the liver that stores bile and squeezes it into the gut to break down fats.",
	kidney_left: "One of two bean-shaped organs that filter waste out of the blood and make urine. This is the left one.",
	kidney_right: "One of two bean-shaped organs that filter waste out of the blood and make urine. This is the right one.",
	liver: "A large organ that filters the blood, processes nutrients, and makes bile. It quietly handles hundreds of jobs that keep you alive.",
	lung_left: "The left lung, one of the pair you breathe with, moving oxygen into the blood and carbon dioxide out.",
	lung_right: "The right lung, one of the pair you breathe with, moving oxygen into the blood and carbon dioxide out.",
	pancreas: "An organ behind the stomach that makes digestive enzymes and insulin, the hormone that keeps blood sugar in check.",
	pancreas_body: "The middle section of the pancreas.",
	pancreas_head: "The wide end of the pancreas, nestled into the C-shaped curve of the duodenum.",
	pancreas_tail: "The narrow end of the pancreas, reaching over toward the spleen.",
	pancreatic_duct: "The channel that carries digestive juices from the pancreas into the small intestine.",
	pancreatic_lesion: "An abnormal spot in the pancreas. It may be harmless, but it's the kind of thing a doctor will want to look at closely.",
	postcava: "Also called the inferior vena cava: the large vein that returns blood from the lower body back up to the heart.",
	prostate: "A small gland below the bladder in men that adds fluid to semen.",
	spleen: "An organ near the stomach that filters the blood and helps the immune system fight infection.",
	stomach: "The muscular pouch that mixes food with acid and starts breaking it down.",
	superior_mesenteric_artery: "A major artery off the aorta that supplies most of the small intestine and part of the colon.",
	veins: "Blood vessels that carry blood back toward the heart.",
	intestine: "The long, coiled tube where most digestion and nutrient absorption happen.",
	renal_vein_left: "The vein that drains filtered blood from the left kidney back toward the heart.",
	renal_vein_right: "The vein that drains filtered blood from the right kidney back toward the heart.",
	cbd_stent: "A small tube a doctor places to hold the bile duct open so bile can drain properly.",
};
